Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteGiayKingShoes.Models;

namespace WebsiteGiayKingShoes.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        dbDataContext db = new dbDataContext();
        public ActionResult Index()
        {
            return View(db.Users);
        }

        public ActionResult NavAdminPartial()
        {
            return PartialView();
        }

        public ActionResult SlideBarPartial()
        {
            return PartialView();
        }

        public ActionResult SpinnerPartial()
        {
            return PartialView();
        }


    }
}

Controllers/SP_CSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteGiayKingShoes.Controllers
{
    [RateLimit]
    public class SP_CSController : Controller
    {
        // GET: SP_CS
        public ActionResult CSKH()
        {
            return View();
        }
        public ActionResult ThanhToan()
        {
            return View();
        }

        public ActionResult HuongDanMuaHang()
        {
            return View();
        }

        public ActionResult CheDoBaoHanh()
        {
            return View();
        }

        public ActionResult ChinhSachDoiHang()
        {
            return View();
        }

        public ActionResult BaoMat()
        {
            return View();
        }

        public ActionResult ChinhSachGiaoNhan()
        {
            return View();
        }

    }
}

Controllers/SearchProController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteGiayKingShoes.Models;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;
namespace WebsiteGiayKingShoes.Controllers
{
    [RateLimit]
    public class SearchProController : Controller
    {
         dbDataContext db = new dbDataContext();
        public ActionResult Search(int? page, string size, string price, string sort, string searchString, int pageSize = 18)
        {
            var kq = db.SANPHAMs.Include(b => b.DANHMUC).Include(b => b.SizeSanPhams);

            // Filter by search string
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                kq = kq.Where(b =>
                    b.TenSP.ToLower().Contains(searchString) ||
                    b.CodeSP.ToLower().Contains(searchString) ||
                    b.DANHMUC.TenDM.ToLower().Contains(searchString));
            }

            // Filter by size
            if (!string.IsNullOrEmpty(size) && size != "all")
            {
                kq = kq.Where(b => b.SizeSanPhams.Any(s => s.Size == size));
            }

            // Filter by price
            if (!string.IsNullOrEmpty(price) && price != "all")
            {
                switch (price)
                {
                    case "under3tr":
                        kq = kq.Where(b => b.GiaBan < 3000000);
                        break;
                    case "3to5":
                        kq = kq.Where(b => b.GiaBan >= 3000000 && b.GiaBan <= 5000000);
                        break;
                    case "5to10":
                        kq = kq.Where(b => b.GiaBan >= 5000000 && b.GiaBan <= 10000000);
                        break;
                    case "10to15":
                        kq = kq.Where(b => b.GiaBan >= 10000000 && b.GiaBan <= 15000000);
                        break;
                    case "over15":
                        kq = kq.Where(b => b.GiaBan > 15000000);
                        break;
                        // Add additional cases for more price ranges if needed
                }
            }

            // Apply sorting
            switch (sort)
            {
                case "latest":
                    kq = kq.OrderByDescending(b => b.NgayCapNhat);
                    break;
             /*   case "popular":
                    // Add logic for popular sorting
                    break;  */
                case "priceHighToLow":
                    kq = kq.OrderByDescending(b => b.GiaBan);
                    break;
                case "priceLowToHigh":
                    kq = kq.OrderBy(b => b.GiaBan);
                    break;
                default:
                    // Default sorting, if needed
                    break;
            }

            // Pagination
            int pageNumber = page ?? 1;
            int totalItems = kq.Count();
            var pagedData = kq.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();

            // Create a PagedList and return it to the view
            var pagedList = new StaticPagedList<SANPHAM>(pagedData, pageNumber, pageSize, totalItems);
            return View(pagedList);
        }



    }
}

Views/Shared/FooterPartial.cshtml
<footer>
    <div class="footer-row">
        <div class="footer-col">
            <h2>Về King Shoes <div class=underline><span></span></div></h2>
            <i class="fa fa-hand-o-right" aria-hidden="true"></i>
            <span>
                Nổi sợ vì mua giày kém chất lượng<br>giày fake từ này không còn lo lắng vì<br> đã
                có KING SHOES hàng chính hãng nhập <br>từ US, full box, nguyên tem.
            </span>
            <ul class="social-icon">
                <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.youtube.com/" target="_blank"><i class="fa fa-youtube"></i></a></li>
            </ul>
        </div>
        <div class="footer-col">
            <h2>Liên hệ <div class=underline><span></span></div></h2>
            <ul class="info">
                <li>
                    <span><i class="fa fa-map-marker"></i></span>
                    <span>13 Trần Văn Ơn, TDM, Bình Dương</span>
                </li>
                <br>
                <li>
                    <span><i class="fa fa-phone"></i></span>
                    <span>+84 1234567890</span>
                </li>
                <br>
                <li>
                    <span><i class="fa fa-envelope"></i></span>
                    <span>kingshoes@gmail.com.vn</span>
                </li>
        </div>
        <div class="footer-col">
            <h2>Hỗ trợ<div class=underline><span></span></div></h2>
            <ul>
                <li>@Html.ActionLink("Chăm sóc khách hàng", "CSKH", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
                <li>@Html.ActionLink("Thanh toán", "ThanhToan", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
                <li>@Html.ActionLink("Hướng dẫn mua hàng", "HuongDanMuaHang", "SP_CS", null, new { style = "color:white" })</li>
                <Br>

            </ul>
        </div>
        <div class="footer-col">
            <h2>Bản đồ <div class=underline><span></span></div></h2>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.7682177471615!2d106.67213421480261!3d10.98085989218299!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d12730e488c3%3A0xfd39431733c080a4!2zMDYgVHLhuqduIFbEg24gxqBuLCBQaMO6IEhvw6AsIFRo4bunIEThuqd1IE3hu5l0LCBCw6xuaCBExrDGoW5n!5e0!3m2!1svi!2s!4v1647254460956!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="footer-col">
            <h2>Chứng nhận <div class=underline><span></span></h2>
            <a href="http://online.gov.vn/Home/WebDetails/86431" target="_blank"><img alt="" height="104" src="https://kingshoes.vn/data/upload/media/logoSaleNoti.png" width="270"></a>
        </div>
        <div class="footer-col">
            <h2>Chính sách <div class=underline><span></span></div> </h2>
            <ul>
                <li>@Html.ActionLink("Chế độ bảo hành", "CheDoBaoHanh", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
                <li>@Html.ActionLink("Chính sách đổi hàng", "ChinhSachDoiHang", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
                <li>@Html.ActionLink("Bảo mật thông tin", "BaoMat", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
                <li>@Html.ActionLink("Chính sách giao nhận", "ChinhSachGiaoNhan", "SP_CS", null, new { style = "color:white" })</li>
                <Br>
            </ul> 
        </div>
    </div>
    <hr>

    <p class="copyright" style=color:white>© Bản quyền thuộc về King Shoes </p>

</footer>

Views/Shared/LayoutUser.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="~/images/title.png">
    <title>King Shoes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    @Html.Partial("NavPartial")



    <div>
        @RenderBody()
    </div>
    @Html.Partial("VoucherPartial")
    @Html.Partial("FooterPartial")


</body>
</html>

Views/Shared/NavPartial.cshtml
  @using  WebsiteGiayKingShoes.Models;

@{
    User kh = (User)Session["TaiKhoan"];
}



<header id="header">

    <a href="~/Home/Index" class="logo">
        <img src="~/images/logo.png" alt="">
    </a>

    <div class="navbar">
        <ul>
            <li><a href="~/Home/Intro">GIỚI THIỆU</a></li>
            <li><a href="~/Home/Nike">NIKE</a></li>
            <li><a href="~/Home/Adidas">ADIDAS</a></li>
            <li><a href="~/Home/Jordan">JORDAN</a></li>
            <li><a href="~/Home/Yeezy">YEEZY</a></li>
            <li><a href="~/Home/Blog">BLOG</a></li>
            <li><a href="~/Home/SpaShoes">SPA GIÀY</a></li>
            <li><a href="~/Home/Contact">LIÊN HỆ</a></li>
        </ul>
    </div>



    <div class="icons">
        <div class="fas fa-search" id="search-btn"></div>
        <a href="@Url.Action("WishList", "WishList")"><div class="fas fa-heart" id="heart-btn"></div></a>
        @Html.Action("GioHangPartial", "Cart")

        @*
            <!-- Modal để hiển thị danh sách sản phẩm -->
            <div id="product-details-modal" class="modal">
                <div class="modal-content">
                    <div id="product-image">
                        <img src="product-image-url.jpg" alt="Product Image">
                    </div>
                    <div id="product-info">
                        <h2 id="product-name">Tên Sản Phẩm</h2>
                        <p id="product-price">Giá: $99.99</p>
                        <p id="product-size">Size: M</p>
                    </div>
                    <div id="product-actions">
                        <p id="total-price">Tổng giá tiền: $99.99</p>
                        <button id="buy-button">Mua</button>
                    </div>
                </div>
            </div>

            <style>
                .modal {
                    display: none;
                    position: fixed;
                    top: 0;

                    width: 100%;
                    height: 100%;
                }

                .modal-content {
                    background-color: #f0f0f0;
                    width: 60%;
                    max-width: 400px;
                    margin: 120px 20px 0 auto; /* Điều chỉnh margin để đẩy modal gần sát phải */
                    padding: 20px;
                    border-radius: 5px;
                    position: relative;
                }
            </style>

            <script>
                // Lấy tham chiếu đến các phần tử HTML
                const cartBtn = document.getElementById("cart-btn");
                const modal = document.getElementById("product-details-modal");

                // Xử lý sự kiện khi click vào icon cart
                cartBtn.addEventListener("click", () => {
                    modal.style.display = "block";
                });


                // Đóng modal nếu người dùng click bên ngoài nó
                window.addEventListener("click", (event) => {
                    if (event.target === modal) {
                        modal.style.display = "none";
                    }
                });




            </script>

        *@


        @if (Session["TaiKhoan"] != null)
        {
            <div class="fas fa-user" id="user-btn"></div>
            <div class="dropdown-content" id="user-dropdown">
                <i id="user-tie-icon" class="fas fa-user-tie"></i>
                <p id="centered-paragraph">@kh.HoTen</p>
                <a href="#"><i class="fas fa-info-circle"></i> Thông tin cá nhân</a>
                @if (kh.VaiTro == 0) // Nếu người dùng là Admin
                {
                    <a href="@Url.Action("Index", "HomeAdmin", new { area = "Admin" })"><i class="fas fa-cogs"></i> Quản lý Website</a>
                }
                <a href="#"><i class="fas fa-cog"></i> Cài đặt</a>
                <a href="@Url.Action("Logout", "User")"><i class="fas fa-sign-out-alt"></i> Đăng xuất</a>



            </div>
        }
        else
        {
            <a href="~/User/Account"><div class="fas fa-sign-in-alt" id="signin-btn"></div></a>
        }


        <div class="fas fa-bars" id="menu-btn"></div>
    </div>

  

    @using (Html.BeginForm("Search", "SearchPro", FormMethod.Get, new { @class = "search-form" }))
    {
        <input type="search" id="search-box" value="@ViewBag.Keyword" name="searchString" placeholder="Nhập vào đây....">
        <label for="search-box" class="fas fa-search"></label>
    }

</header>


<style>
    #user-dropdown {
        position: absolute;
        top: 100%;
        right: 0;
        display: none;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
        z-index: 1;
        padding: 8px;
        transition: display 0.2s ease-in-out;
    }

    #user-tie-icon {
        text-align: center; /* Căn văn bản giữa theo chiều ngang */
        display: flex;
        justify-content: center; /* Căn nội dung theo chiều ngang */
        align-items: center; 
    }

    #centered-paragraph {
        text-align: center; /* Center the text horizontally */
        font-size: 25px; /* Adjust the font size as needed */
    }

        #user-dropdown a {
            display: block;
            text-decoration: none;
            color: #333;
            padding: 10px;
            font-size: 20px;
        }

            #user-dropdown a:hover {
                background-color: #f2f2f2;
            }
</style>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        const userBtn = document.getElementById("user-btn");
        const userDropdown = document.getElementById("user-dropdown");

        // Function to close the dropdown when clicking outside
        const closeDropdown = function (event) {
            if (!userBtn.contains(event.target) && !userDropdown.contains(event.target)) {
                userDropdown.style.display = "none";
            }
        };

        userBtn.addEventListener("click", function (event) {
            if (userDropdown.style.display === "block") {
                userDropdown.style.display = "none";
            } else {
                userDropdown.style.display = "block";
                // Add a click event listener on the document to close the dropdown when clicking outside
                document.addEventListener("click", closeDropdown);
            }

            // Prevent the click event from propagating to the document and immediately closing the dropdown
            event.stopPropagation();
        });
    });
</script>

Views/Shared/SearchValueShoes.cshtml
<form class="timkiem">
    <div>
        <label for="size">Size:</label>
        <select id="size" name="size">
            <option value="all" selected>Tất cả</option>
            <option value="39">39</option>
            <option value="40">40</option>
            <option value="41">41</option>
            <option value="42">42</option>
            <option value="43">43</option>

        </select>
    </div>
    <div>
        <label for="price">Giá:</label>
        <select id="price" name="price">
            <option value="all" selected>Tất cả</option>
            <option value="under3tr">Dưới 3 triệu</option>
            <option value="3to5">Từ 3 triệu đến 5 triệu</option>
            <option value="5to10">Từ 5 triệu đến 10 triệu</option>
            <option value="10to15">Từ 10 triệu đến 15 triệu</option>
            <option value="over15">Trên 15 triệu</option>
        </select>
    </div>
    <div>
        <label for="sort">Sắp xếp theo:</label>
        <select id="sort" name="sort">
            <option value="all" selected>Tất cả</option>
            <option value="latest">Mới nhất</option>
            @* <option value="popular">Phổ biến nhất</option> *@
            <option value="priceHighToLow">Giá cao đến thấp</option>
            <option value="priceLowToHigh">Giá thấp đến cao</option>
        </select>
    </div>
    <input type="submit" value="Tìm Kiếm" class="custom-button">
</form>

Views/Shared/TinTuc.cshtml
<div class="news-section">
    <h1>Tin Tức Mới</h1>
    @foreach (var tintuc in ViewBag.NewsArticles)
    {
        <a href="@Url.Action("BlogDetail", new { id = tintuc.MaTinTuc })">
            <div class="news-item">
                <div class="news-img">
                    <img src="~/images/TinTuc/@tintuc.AnhBia" alt="Hình ảnh tin tức 1">
                </div>
                <div class="news-nd">
                    <h3>@tintuc.Title</h3>
                    <p>@tintuc.Publish_date.ToString("dd/MM/yyyy")</p>
                </div>
            </div>
            <!-- Thêm tin tức khác theo cùng mẫu -->
        </a>
            }
            @Html.ActionLink("Xem thêm", "Blog")

    </div>


<style>


</style>

Views/Shared/VoucherPartial.cshtml
<section class="newsletter">

    <div class="content">
        <h3>Đăng kí nhận code</h3>
        <p>...Nhận ngay <span>Voucher 100k</span> từ chúng tôi</p>
        <form action="">
            <input type="email" placeholder="Nhập email của bạn" class="box">
            <input type="submit" value="send" class="btn">
        </form>
    </div>

</section>